export interface IApiParameterInfo
{
  sectionName: string,
  className: string,
  uiFieldType: string,
  key: string,
  label: string,
  isMandatory: string,
  lookupApiName: string,
  serviceName: string,
  createPageUrl: string,
  hide: string,
  parentLookupModelName: string,
  parentLookupFieldName: string,
  hideForUserType: string,
  optionsListName: string,
  showHideDependentFields: string,
  showHideSections: string,
  displayClassName: string,
  showImage: string,
  additionalProperties: string,
  isInjectedField: string,
  dataType: string,
  disableCommasInNumberDisplay: string,
  rowNumber: string,
  gridColumnsCount: string,
  isOtherService: boolean, 
  otherServiceContextPath: string,
  retrievePageUrl: string,
  placeholder: string,
}
