import {IEntityAttachmentDto} from "./../../dto-base";

export interface retrieveStudentListDataObject{
  isSelected: boolean,
  firstName: string,
  lastName: string,
  classInfoUUID: string,
  classInfoDisplayText: string, 
  sectionUUID: string,
  sectionDisplayText: string, 
  gender: string, 
  isAccountActive: boolean, 
  dateOfBirth: string, 
  dynamicLocationUUID: string,
  dynamicLocationDisplayText: string, 
  staticLocationUUID: string,
  staticLocationDisplayText: string, 
  location1UUID: string,
  location1DisplayText: string, 
  profilePicture: Array<IEntityAttachmentDto>,
  publicPic: Array<IEntityAttachmentDto>,
  age: number, 
  percentage: number, 
  collegeId: number,
  dateTimeField: string,
  dateTimeWithSecondsField: string,
  timeField: string,
  timeWithSecondsField: string,
  isPassed: boolean, 
  passMarks: number, 
  failMarks: number, 
  grade: string, 
  gradeAMarks: number, 
  gradeBMarks: number, 
  gradeCMarks: number, 
  studentUUID: string,
  ageForUpdate : string
  genderForUpdate : string

}

export interface retrieveStudentListSearchFilter {
  studentUUID: string,
  firstName: string,
  lastName: string,
  classInfoUUID: any,
  sectionUUID: any,
  gender: string, 
  isAccountActive: boolean, 
  dateOfBirthFrom: string, 
  dateOfBirthTo: string, 
  dynamicLocationUUID: any,
  staticLocationUUID: any,
  location1UUID: any,
  age: number, 
  percentage: number, 
  collegeId: number,
  dateTimeField: string,
  dateTimeWithSecondsField: string,
  timeField: string,
  timeWithSecondsField: string,
  isPassed: boolean, 
  passMarks: number, 
  failMarks: number, 
  grade: string, 
  gradeAMarks: number, 
  gradeBMarks: number, 
  gradeCMarks: number, 
  pageNumber: number,
  pageSize: number
}
