import {FileAttachmentDto, IDto} from "./../../dto-base";

export interface IRetrieveStudentDto extends IDto 
{
  facultyUUID: string,
  facultyDisplayText : string,
  firstName: string,
  lastName: string,
  classInfoUUID: string,
  classInfoDisplayText : string,
  sectionUUID: string,
  sectionDisplayText : string,
  gender: string, 
  isAccountActive: boolean, 
  dateOfBirth: string, 
  dynamicLocationUUID: string,
  dynamicLocationDisplayText : string,
  staticLocationUUID: string,
  staticLocationDisplayText : string,
  location1UUID: string,
  location1DisplayText : string,
  faculty1UUID: string,
  faculty1DisplayText : string,
  profilePicture: Array<FileAttachmentDto>,
  publicPic: Array<FileAttachmentDto>,
  age: number, 
  percentage: number, 
  collegeId: number,
  dateTimeField: string,
  dateTimeWithSecondsField: string,
  timeField: string,
  timeWithSecondsField: string,
  isPassed: boolean, 
  passMarks: number, 
  failMarks: number, 
  grade: string, 
  gradeAMarks: number, 
  gradeBMarks: number, 
  gradeCMarks: number, 
  success :  number,
  alert : string
}
