export interface IUpdateStudentAllDetailsRequestModel {
  studentUUID: string,
  firstName: string,
  lastName: string,
  gender: string, 
  isAccountActive: boolean, 
  dateOfBirth: string, 
  staticLocationUUID: string,
  dynamicLocationUUID: string,
  profilePicture?: File,
  age: number, 
  percentage: number, 
  collegeId: number,
  dateTimeField: string,
  dateTimeWithSecondsField: string,
  timeField: string,
  timeWithSecondsField: string,
  isPassed: boolean, 
  passMarks: number, 
  failMarks: number, 
  grade: string, 
  gradeAMarks: number, 
  gradeBMarks: number, 
  gradeCMarks: number, 
  timeZone ? : string
}
