export interface IUpdateInvoiceLineItemRequestModel {
  productName: string,
  lastName: string,
  gender: string, 
  faculty1UUID: string,
  isAccountActive: boolean, 
  dateOfBirth: string, 
  dynamicLocationUUID: string,
  staticLocationUUID: string,
  age: number, 
  percentage: number, 
  collegeId: number,
  dateTimeField: string,
  dateTimeWithSecondsField: string,
  timeField: string,
  timeWithSecondsField: string,
  isPassed: boolean, 
  passMarks: number, 
  failMarks: number, 
  invoiceLineItemUUID: string,
}
