export interface IUpdateEmployeeSSRequestModel {
  firstName: string,
  lastName: string,
  emailId: string,
  noOfChildren: number,
  dateTimeWithSecondsField: string,
  enableJobDetails: boolean, 
  attachments?: File,
  locationUUID: string,
  joininigDate: string, 
  gender: string, 
  dateTimeField: string,
  timeField: string,
  timeWithSecondsField: string,
  location1UUID: string,
  location2UUID: string,
  salary: number, 
  hike: number, 
  objectId: number,
  isUserValidated: boolean, 
  employeeUUID: string,
}
